### PR TITLE
MEI-17854 Python 3.7 support

### PR DESCRIPTION
**Pull request by wasifarbisoft**

### CODE REVIEW

**Comment by wasifarbisoft** [comment]
@mudassir-hafeez 
Since master branch was way ahead and we are using 1.2.4 version so I have created a new branch 1.2.5-master which is at same state as that of 1.2.5 version and created PR against that branch

**Comment by mudassir-hafeez** [comment]
@wasifarbisoft Can you please rename the base branch to some meaningful name `edx-notifications-v2`as it would be using ahead for Django upgrade of Apros?

**Comment by mudassir-hafeez** [comment]
Also, change [tox.ini](https://github.com/mckinseyacademy/edx-notifications/blob/1.2.5-master/tox.ini#L2) to add capability to run tests with py37-django22 for now.

**Comment by wasifarbisoft** [comment]
@mudassir-hafeez 
Please review https://github.com/mckinseyacademy/edx-notifications/pull/2
for new new branch

**Pull request closed without merging**
